name: minigptv
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py39h7deecbd_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py39h06a4308_0
  - comm=0.2.1=pyhd8ed1ab_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.8.0=py39h06a4308_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - h2=4.0.0=py39h06a4308_3
  - hpack=4.0.0=py_0
  - hyperframe=6.0.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.2=pyhd33586a_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py39hf3d152e_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.26.2=py39h5f9d8c6_0
  - numpy-base=1.26.2=py39hb5e798b_0
  - openai=1.3.6=py39h06a4308_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py39h1128e8f_0
  - pandas-stubs=1.5.3.230203=py39h06a4308_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2023.3.post1=py39h06a4308_0
  - pyzmq=25.1.2=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - rfc3986=1.4.0=pyhd3eb1b0_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - types-pytz=2022.4.0.0=py39h06a4308_1
  - tzdata=2023c=h04d1e81_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.29.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - altair==5.2.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arxiv==2.1.0
      - asgiref==3.7.2
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrdict==2.0.1
      - attrs==23.1.0
      - autopep8==2.1.0
      - babel==2.14.0
      - backoff==2.2.1
      - backpack-for-pytorch==1.6.0
      - backports-tarfile==1.1.0
      - bce-python-sdk==0.9.6
      - bcrypt==4.1.2
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.1
      - bleach==6.1.0
      - blinker==1.7.0
      - blis==0.7.11
      - braceexpand==0.1.7
      - bs4==0.0.2
      - build==1.1.1
      - bypy==1.8.5
      - cachetools==5.3.2
      - catalogue==2.0.10
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - chroma-hnswlib==0.7.3
      - chromadb==0.4.24
      - click==8.1.7
      - clip==1.0
      - cloudpathlib==0.16.0
      - cma==3.4.0
      - cmake==3.27.9
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - commonmark==0.9.1
      - confection==0.1.4
      - contourpy==1.2.0
      - cryptography==42.0.5
      - cssselect==1.2.0
      - cssutils==2.10.2
      - cvxopt==1.3.2
      - cycler==0.12.1
      - cymem==2.0.8
      - cython==3.0.10
      - dataclasses-json==0.6.4
      - datasets==2.17.1
      - decord==0.6.0
      - deepdiff==8.0.1
      - deepspeed==0.14.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dgl==2.1.0
      - dglgo==0.0.2
      - diffusers==0.25.0
      - dill==0.3.8
      - dirtyjson==1.0.8
      - dnspython==2.6.1
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - docutils==0.20.1
      - editdistance==0.8.1
      - efficientnet-pytorch==0.7.1
      - einops==0.7.0
      - einops-exts==0.0.4
      - emoji==2.14.0
      - et-xmlfile==1.1.0
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.0
      - faiss-gpu==1.7.2
      - faker==30.8.2
      - fastapi==0.104.1
      - fastjsonschema==2.19.1
      - fastnlp==1.0.1
      - feedparser==6.0.10
      - ffmpy==0.3.1
      - filelock==3.13.1
      - filetype==1.2.0
      - fire==0.5.0
      - flask==3.0.2
      - flask-babel==4.0.0
      - flask-jwt-extended==4.6.0
      - flask-sqlalchemy==3.1.1
      - flatbuffers==23.5.26
      - fonttools==4.46.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - ftfy==6.1.3
      - func-timeout==4.3.5
      - future==1.0.0
      - gensim==4.3.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-ai-generativelanguage==0.4.0
      - google-api-core==2.15.0
      - google-auth==2.29.0
      - google-auth-oauthlib==1.2.0
      - google-cloud-aiplatform==1.48.0
      - google-cloud-bigquery==3.20.1
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.12.3
      - google-cloud-storage==2.16.0
      - google-crc32c==1.5.0
      - google-generativeai==0.3.2
      - google-resumable-media==2.7.0
      - googleapis-common-protos==1.62.0
      - gradio==3.47.1
      - gradio-client==0.6.0
      - greenlet==3.0.3
      - griffe==0.45.1
      - grpc-google-iam-v1==0.13.0
      - grpcio==1.62.1
      - grpcio-status==1.34.0
      - gunicorn==23.0.0
      - h11==0.14.0
      - hjson==3.1.0
      - html5lib==1.1
      - httpcore==1.0.6
      - httptools==0.6.1
      - httpx==0.25.2
      - httpx-sse==0.4.0
      - huggingface-hub==0.23.0
      - humanfriendly==10.0
      - idna==3.6
      - imageio==2.33.1
      - imagesize==1.4.1
      - imgaug==0.4.0
      - importlib-metadata==6.11.0
      - importlib-resources==6.1.1
      - iopath==0.1.10
      - ipywidgets==8.1.2
      - isodate==0.6.1
      - isoduration==20.11.0
      - isort==5.13.2
      - itsdangerous==2.1.2
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jax==0.4.26
      - jaxlib==0.4.26
      - jeepney==0.8.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.25
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpickle==3.0.3
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.10
      - keyring==25.1.0
      - kiwisolver==1.4.5
      - kornia==0.7.4
      - kornia-rs==0.1.7
      - kubernetes==29.0.0
      - lagent==0.2.2
      - langchain==0.3.7
      - langchain-community==0.3.5
      - langchain-core==0.3.15
      - langchain-text-splitters==0.3.2
      - langcodes==3.3.0
      - langdetect==1.0.9
      - langsmith==0.1.140
      - layoutparser==0.3.4
      - lazy-loader==0.3
      - levenshtein==0.23.0
      - lightning-utilities==0.11.2
      - lit==17.0.6
      - litellm==1.31.3
      - littleutils==0.2.2
      - llama-index==0.10.18
      - llama-index-agent-openai==0.1.5
      - llama-index-cli==0.1.8
      - llama-index-core==0.10.18.post1
      - llama-index-embeddings-openai==0.1.6
      - llama-index-indices-managed-llama-cloud==0.1.3
      - llama-index-legacy==0.9.48
      - llama-index-llms-openai==0.1.7
      - llama-index-multi-modal-llms-openai==0.1.4
      - llama-index-program-openai==0.1.4
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.9
      - llama-index-readers-llama-parse==0.1.3
      - llama-index-vector-stores-chroma==0.1.6
      - llama-parse==0.3.8
      - llamaindex-py-client==0.1.13
      - llava==1.2.2.post1
      - llmgraph==1.1.0
      - lmdb==1.4.1
      - loguru==0.7.2
      - loralib==0.1.2
      - lxml==5.2.1
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markdown2==2.4.13
      - markupsafe==2.1.3
      - marshmallow==3.21.1
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mediapipe==0.10.11
      - minigemini==1.0.0
      - mistune==3.0.2
      - ml-dtypes==0.4.0
      - mmengine==0.10.4
      - mmh3==4.1.0
      - monotonic==1.6
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - narwhals==1.48.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.2.1
      - neuralkg==1.0.21
      - nh3==0.2.17
      - nibabel==5.3.2
      - ninja==1.11.1.1
      - nltk==3.9.1
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - numpydoc==1.7.0
      - nvflare==2.6.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - ogb==1.3.6
      - olefile==0.47
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime==1.17.1
      - open-clip-torch==2.24.0
      - opencv-contrib-python==4.6.0.66
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.9.0.80
      - openpyxl==3.1.2
      - opentelemetry-api==1.23.0
      - opentelemetry-exporter-otlp-proto-common==1.23.0
      - opentelemetry-exporter-otlp-proto-grpc==1.23.0
      - opentelemetry-instrumentation==0.44b0
      - opentelemetry-instrumentation-asgi==0.44b0
      - opentelemetry-instrumentation-fastapi==0.44b0
      - opentelemetry-proto==1.23.0
      - opentelemetry-sdk==1.23.0
      - opentelemetry-semantic-conventions==0.44b0
      - opentelemetry-util-http==0.44b0
      - opt-einsum==3.3.0
      - orderly-set==5.2.2
      - orjson==3.9.15
      - outdated==0.2.2
      - overrides==7.7.0
      - paddleocr==2.7.3
      - pandocfilters==1.5.1
      - pdf2docx==0.5.8
      - pdf2image==1.17.0
      - pdfminer==20191125
      - pdfminer-six==20231228
      - pdfplumber==0.11.4
      - peft==0.11.1
      - phx-class-registry==4.0.6
      - pi-heif==0.20.0
      - pillow==10.1.0
      - pip==24.3.1
      - pkginfo==1.10.0
      - plotly==6.2.0
      - portalocker==2.8.2
      - posthog==3.5.0
      - pot==0.9.5
      - premailer==3.10.0
      - preshed==3.0.9
      - prettytable==3.16.0
      - progressbar2==4.2.0
      - prometheus-client==0.20.0
      - proto-plus==1.23.0
      - protobuf==3.20.2
      - psutil==5.9.4
      - pulsar-client==3.4.0
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyclipper==1.3.0.post5
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pycodestyle==2.11.1
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.6.1
      - pydeck==0.9.1
      - pydeprecate==0.3.1
      - pydicom==2.4.4
      - pydub==0.25.1
      - pyhocon==0.3.61
      - pyjwt==2.10.1
      - pylibjpeg==2.0.1
      - pylibjpeg-libjpeg==2.0.0
      - pymongo==4.6.3
      - pymupdf==1.23.26
      - pymupdfb==1.23.22
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - pypdf==4.1.0
      - pypdfium2==4.30.0
      - pypika==0.48.9
      - pyproject-hooks==1.0.0
      - pyre-extensions==0.0.29
      - pytesseract==0.3.13
      - python-docx==1.1.0
      - python-dotenv==1.0.1
      - python-graphviz==0.20.3
      - python-iso639==2024.10.22
      - python-json-logger==2.0.7
      - python-levenshtein==0.23.0
      - python-magic==0.4.27
      - python-multipart==0.0.6
      - python-oxmsg==0.0.1
      - python-utils==3.8.1
      - pytorch-lightning==2.3.0
      - pyvis==0.3.2
      - pyyaml==6.0.1
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rapidfuzz==3.6.1
      - rarfile==4.2
      - rdflib==7.0.0
      - rdkit-pypi==2022.9.5
      - readme-renderer==43.0
      - referencing==0.32.0
      - regex==2022.10.31
      - replicate==1.0.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.6.0
      - rpds-py==0.13.2
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.1
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==2.19.2
      - setproctitle==1.3.3
      - setuptools==59.5.0
      - sglang==0.1.14
      - sgmllib3k==1.0.0
      - shapely==2.0.3
      - shortuuid==1.0.13
      - shtab==1.7.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - some-package==0.1
      - sounddevice==0.4.6
      - soupsieve==2.5
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sparqlwrapper==2.0.0
      - sphinx==7.2.6
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sqlalchemy==2.0.16
      - srsly==2.4.8
      - starlette==0.27.0
      - streamlit==1.40.0
      - streamlit-chat==0.1.1
      - striprtf==0.0.26
      - sty==1.0.6
      - svgwrite==1.4.3
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - thinc==8.2.3
      - threadpoolctl==3.2.0
      - tifffile==2023.12.9
      - tiktoken==0.6.0
      - timeout-decorator==0.5.0
      - timm==1.0.3
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==2.0.0
      - torch-scatter==2.1.2
      - torchaudio==2.0.1
      - torchdata==0.7.1
      - torchinterp1d==1.1
      - torchmetrics==1.3.2
      - torchvision==0.15.1
      - torchviz==0.0.3
      - torchxrayvision==1.2.1
      - tornado==6.4
      - tqdm==4.66.2
      - transformers==4.41.0
      - transformers-stream-generator==0.0.5
      - transforms3d==0.4.2
      - triton==2.0.0
      - trl==0.7.11
      - twine==5.0.0
      - typer==0.9.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tyro==0.7.3
      - unfoldnd==0.2.3
      - unstructured==0.16.5
      - unstructured-client==0.25.0
      - unstructured-inference==0.8.1
      - unstructured-pytesseract==0.3.13
      - uri-template==1.3.0
      - urllib3==2.1.0
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - validators==0.28.1
      - vertexai==1.48.0
      - visual-genome==1.1.1
      - visualdl==2.5.3
      - wandb==0.19.1
      - wasabi==1.1.2
      - watchdog==4.0.0
      - watchfiles==0.21.0
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.12
      - weasel==0.3.4
      - webcolors==1.13
      - webdataset==0.2.48
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==11.0.3
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.10
      - wilds==2.0.0
      - wrapt==1.16.0
      - xformer==1.0.1
      - xformers==0.0.19
      - xlsxwriter==3.2.0
      - xtuner==0.1.19
      - xxhash==3.4.1
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.17.0
